local harpoon = require('harpoon')
harpoon:setup()
vim.keymap.set('n', '<leader>p', function()
  harpoon:list():append()
end, { desc = '[P]ush to harpoon list' })
vim.keymap.set('n', '<leader>i', function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = 'Toggle harpoon' })
vim.keymap.set('n', '<leader>h', function()
  harpoon:list():select(1)
end, { desc = 'Harpoon 1st file' })
vim.keymap.set('n', '<leader>j', function()
  harpoon:list():select(2)
end, { desc = 'Harpoon 2nd file' })
vim.keymap.set('n', '<leader>k', function()
  harpoon:list():select(3)
end, { desc = 'Harpoon 3rd file' })
vim.keymap.set('n', '<leader>l', function()
  harpoon:list():select(4)
end, { desc = 'Harpoon 4th file' })
