local harpoon = require('harpoon')
harpoon:setup()
vim.keymap.set('n', '<A-p>', function()
  harpoon:list():append()
end, { desc = '[P]ush to harpoon list' })
vim.keymap.set('n', '<A-t>', function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = '[T]oggle harpoon' })
vim.keymap.set('n', '<A-h>', function()
  harpoon:list():select(1)
end, { desc = 'Harpoon 1st file' })
vim.keymap.set('n', '<A-j>', function()
  harpoon:list():select(2)
end, { desc = 'Harpoon 2nd file' })
vim.keymap.set('n', '<A-k>', function()
  harpoon:list():select(3)
end, { desc = 'Harpoon 3rd file' })
vim.keymap.set('n', '<A-l>', function()
  harpoon:list():select(4)
end, { desc = 'Harpoon 4th file' })
