local harpoon = require('harpoon')
harpoon:setup()
vim.keymap.set('n', '<leader>ha', function()
  harpoon:list():append()
end, { desc = 'Append to harpoon list' })
vim.keymap.set('n', '<leader>ht', function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = 'Toggle harpoon' })
vim.keymap.set('n', '<leader>hh', function()
  harpoon:list():select(1)
end, { desc = 'Harpoon 1st file' })
vim.keymap.set('n', '<leader>hj', function()
  harpoon:list():select(2)
end, { desc = 'Harpoon 2nd file' })
vim.keymap.set('n', '<leader>hk', function()
  harpoon:list():select(3)
end, { desc = 'Harpoon 3rd file' })
vim.keymap.set('n', '<leader>hl', function()
  harpoon:list():select(4)
end, { desc = 'Harpoon 4th file' })
