require('plugins/cmp')
require('plugins/conform')
-- require('plugins/copilot')
require('plugins/flash')
require('plugins/gitsigns')
require('plugins/harpoon')
require('plugins/lsp')
require('plugins/mini')
require('plugins/noice')
require('plugins/oil')
require('plugins/telescope')
require('plugins/tree')
require('plugins/treesitter')
