{
  imports = [
    ./blink-cmp.nix
    ./conform.nix
    ./copilot.nix
    ./debugprint.nix
    ./diffview.nix
    ./flash.nix
    ./git-conflict.nix
    ./gitsigns.nix
    ./hex.nix
    ./lsp.nix
    ./markdown.nix
    ./mini.nix
    ./noice.nix
    ./oil.nix
    ./spectre.nix
    ./telescope.nix
    ./tree.nix
    ./treesitter.nix
    ./ts-context-commentstring.nix
  ];
}
