{
  imports = [
    ./cmp.nix
    ./conform.nix
    ./copilot.nix
    ./debugprint.nix
    ./diffview.nix
    ./flash.nix
    ./git-conflict.nix
    ./gitsigns.nix
    ./lsp.nix
    ./mini.nix
    ./noice.nix
    ./oil.nix
    ./telescope.nix
    ./tree.nix
    ./treesitter.nix
  ];
}
